spring:
  application:
    name: orderProcessing
  datasource:
    url: jdbc:h2:mem:ordersdb
    driver-class-name: org.h2.Driver
    username: localdb
    password: localdb
  rabbitmq:
    host: localhost
    port: 5672
    username: orderuser
    password: orderpass

jpa:
  hibernate:
    ddl-auto: create-drop
  database-platform: org.hibernate.dialect.H2Dialect

h2:
  console:
    enabled: true

server:
  port: 8080

rabbitmq:
  username: guest
  password: guest

docker:
  compose:
    enabled: false
