spring:
  application:
    name: orderProcessing
  datasource:
    url: jdbc:h2:mem:ordersdb
    driver-class-name: org.h2.Driver
    username: localdb
    password: localdb
  rabbitmq:
    host: localhost
    port: 5672
    username: orderuser
    password: orderpass
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  server:
    port: 8080
